import { Establishment, Event } from '@/types';

export const mockEstablishments: Establishment[] = [
  {
    id: '1',
    name: 'Mana Restaurant',
    category: 'restaurant',
    address: 'Immeuble AGC Vie, face mémorial Savorgnan',
    neighborhood: 'Centre-ville',
    rating: 4.8,
    reviewCount: 128,
    imageUrl: '/images/establishments/mana.jpg',
    phone: '+242 06 728 28 43',
    hours: 'Lun-Sam: 08h-23h · Dim: 10h-22h',
    isOpen: true,
    isPremium: true,
    description: 'Restaurant gastronomique au coeur de Brazzaville, Mana propose une cuisine raffinée mêlant saveurs congolaises et influences internationales.',
    latitude: -4.2634,
    longitude: 15.2429,
  },
  {
    id: '2',
    name: 'Espace Ogasan',
    category: 'lounge',
    address: 'Djiri',
    neighborhood: 'Djiri',
    rating: 4.6,
    reviewCount: 95,
    imageUrl: '/images/establishments/ogasan.jpg',
    isOpen: true,
    latitude: -4.2734,
    longitude: 15.2529,
  },
  {
    id: '3',
    name: 'Le First',
    category: 'bar',
    address: 'Poto-Poto',
    neighborhood: 'Poto-Poto',
    rating: 4.5,
    reviewCount: 76,
    imageUrl: '/images/establishments/first.jpg',
    isOpen: false,
    latitude: -4.2534,
    longitude: 15.2329,
  },
  {
    id: '4',
    name: 'Chez Mama Congo',
    category: 'restaurant',
    address: 'Bacongo',
    neighborhood: 'Bacongo',
    rating: 4.3,
    reviewCount: 54,
    imageUrl: '/images/establishments/mama.jpg',
    isOpen: true,
    latitude: -4.2834,
    longitude: 15.2629,
  },
  {
    id: '5',
    name: 'Rooftop Brazza',
    category: 'lounge',
    address: 'Centre',
    neighborhood: 'Centre',
    rating: 4.7,
    reviewCount: 112,
    imageUrl: '/images/establishments/rooftop.jpg',
    isPremium: true,
    isOpen: true,
    latitude: -4.2634,
    longitude: 15.2529,
  },
  {
    id: '6',
    name: 'Garden Bar',
    category: 'bar',
    address: 'Moungali',
    neighborhood: 'Moungali',
    rating: 4.1,
    reviewCount: 43,
    imageUrl: '/images/establishments/garden.jpg',
    isOpen: true,
    latitude: -4.2434,
    longitude: 15.2229,
  },
];

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Soirée Jazz',
    category: 'Musique',
    date: 'Sam 15 Fév',
    time: '20h',
    establishment: 'Mana Restaurant',
    price: '5 000 FCFA',
    availablePlaces: 42,
    totalPlaces: 80,
    imageUrl: '/images/events/jazz.jpg',
  },
  {
    id: '2',
    title: 'Brunch DJ',
    category: 'Brunch',
    date: 'Dim 16 Fév',
    time: '11h',
    establishment: 'Le First',
    price: 'Gratuit',
    availablePlaces: 15,
    totalPlaces: 40,
    imageUrl: '/images/events/brunch.jpg',
  },
  {
    id: '3',
    title: 'Nuit Salsa',
    category: 'Danse',
    date: 'Ven 21 Fév',
    time: '22h',
    establishment: 'Espace Ogasan',
    price: '3 000 FCFA',
    availablePlaces: 28,
    totalPlaces: 60,
    imageUrl: '/images/events/salsa.jpg',
  },
];