// import { Establishment, Event } from '@/types';

// // Images pour le carousel du Hero
// export const heroImages = [
//   'https://cf.bstatic.com/xdata/images/hotel/max1024x768/246563254.jpg?k=f6401d1ec0d9d3f34990df768fd5d0ac8186daf48bbeb74025e8def6a86d1fb3&o=',
//   'https://cf.bstatic.com/xdata/images/hotel/max1024x768/817052254.jpg?k=2c075509e2a8196301cb4984511faad8d97cd2c75ba4fecc493593102123937b&o=', // Bar
//   'https://res.cloudinary.com/amenitiz/image/upload/c_fill,q_auto:best,w_1200/v1676282731/kkewhjkcage1ytjivu4i.jpg?_a=BACAGSGT',
//   'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=1920&q=80', // Événement
// ];

// export const mockEstablishments = [
//   {
//     id: '1',
//     nom: 'Mana Restaurant',
//     categorie_nom: 'restaurant',
//     categorie_id: 'restaurant',
//     adresse: 'Immeuble AGC Vie, face mémorial Savorgnan',
//     quartier_nom: 'Centre-ville',
//     quartier_id: 'centre-ville',
//     ville_nom: 'Brazzaville',
//     note_moyenne: '4.8',
//     nombre_avis: 128,
//     image_principale: '/images/establishments/mana.jpg',
//     est_featured: true,
//     description: 'Restaurant gastronomique au coeur de Brazzaville, Mana propose une cuisine raffinée mêlant saveurs congolaises et influences internationales.',
//     latitude: -4.2634,
//     longitude: 15.2429,
//   },
//   {
//     id: '2',
//     nom: 'Espace Ogasan',
//     categorie_nom: 'lounge',
//     categorie_id: 'lounge',
//     adresse: 'Djiri',
//     quartier_nom: 'Djiri',
//     quartier_id: 'djiri',
//     ville_nom: 'Brazzaville',
//     note_moyenne: '4.6',
//     nombre_avis: 95,
//     image_principale: '/images/establishments/ogasan.jpg',
//     est_featured: false,
//     latitude: -4.2734,
//     longitude: 15.2529,
//   },
//   {
//     id: '3',
//     nom: 'Le First',
//     categorie_nom: 'bar',
//     categorie_id: 'bar',
//     adresse: 'Poto-Poto',
//     quartier_nom: 'Poto-Poto',
//     quartier_id: 'poto-poto',
//     ville_nom: 'Brazzaville',
//     note_moyenne: '4.5',
//     nombre_avis: 76,
//     image_principale: '/images/establishments/first.jpg',
//     est_featured: false,
//     latitude: -4.2534,
//     longitude: 15.2329,
//   },
//   {
//     id: '4',
//     nom: 'Chez Mama Congo',
//     categorie_nom: 'restaurant',
//     categorie_id: 'restaurant',
//     adresse: 'Bacongo',
//     quartier_nom: 'Bacongo',
//     quartier_id: 'bacongo',
//     ville_nom: 'Brazzaville',
//     note_moyenne: '4.3',
//     nombre_avis: 54,
//     image_principale: '/images/establishments/mama.jpg',
//     est_featured: false,
//     latitude: -4.2834,
//     longitude: 15.2629,
//   },
//   {
//     id: '5',
//     nom: 'Rooftop Brazza',
//     categorie_nom: 'lounge',
//     categorie_id: 'lounge',
//     adresse: 'Centre',
//     quartier_nom: 'Centre',
//     quartier_id: 'centre',
//     ville_nom: 'Brazzaville',
//     note_moyenne: '4.7',
//     nombre_avis: 112,
//     image_principale: '/images/establishments/rooftop.jpg',
//     est_featured: true,
//     latitude: -4.2634,
//     longitude: 15.2529,
//   },
//   {
//     id: '6',
//     nom: 'Garden Bar',
//     categorie_nom: 'bar',
//     categorie_id: 'bar',
//     adresse: 'Moungali',
//     quartier_nom: 'Moungali',
//     quartier_id: 'moungali',
//     ville_nom: 'Brazzaville',
//     note_moyenne: '4.1',
//     nombre_avis: 43,
//     image_principale: '/images/establishments/garden.jpg',
//     est_featured: false,
//     latitude: -4.2434,
//     longitude: 15.2229,
//   },
// ] as any;

// export const mockEvents = [
//   {
//     id: '1',
//     titre: 'Soirée Jazz',
//     type_event_display: 'Musique',
//     date_debut: '2026-02-15T20:00:00Z',
//     date_fin: '2026-02-15T23:00:00Z',
//     etablissement_nom: 'Mana Restaurant',
//     prix: '5000',
//     est_gratuit: false,
//     places_disponibles: 42,
//     nb_places_total: 80,
//     affiche_complete: '/images/events/jazz.jpg',
//     est_complet: false,
//   },
//   {
//     id: '2',
//     titre: 'Brunch DJ',
//     type_event_display: 'Brunch',
//     date_debut: '2026-02-16T11:00:00Z',
//     date_fin: '2026-02-16T14:00:00Z',
//     etablissement_nom: 'Le First',
//     prix: '0',
//     est_gratuit: true,
//     places_disponibles: 15,
//     nb_places_total: 40,
//     affiche_complete: '/images/events/brunch.jpg',
//     est_complet: false,
//   },
//   {
//     id: '3',
//     titre: 'Nuit Salsa',
//     type_event_display: 'Danse',
//     date_debut: '2026-02-21T22:00:00Z',
//     date_fin: '2026-02-22T02:00:00Z',
//     etablissement_nom: 'Espace Ogasan',
//     prix: '3000',
//     est_gratuit: false,
//     places_disponibles: 28,
//     nb_places_total: 60,
//     affiche_complete: '/images/events/salsa.jpg',
//     est_complet: false,
//   },
// ] as any;